spring.application.name=backend
spring.datasource.url=jdbc:h2:mem:smart_campus;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true

app.admin.email=admin@smartcampus.com
app.admin.password=Admin@123
app.admin.full-name=System Admin
app.admin.it-number=ITADMIN01