spring.application.name=nexahub-api
spring.datasource.url=jdbc:postgresql://localhost:5432/nexahub_db
spring.datasource.username=postgres
spring.datasource.password=Riva@2002
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.admin.email=admin@smartcampus.com
app.admin.password=Admin@123
app.admin.full-name=System Admin
app.admin.it-number=ITADMIN01