spring.application.name=nexahub-api
spring.datasource.url=jdbc:mysql://localhost:3306/smart_campus
spring.datasource.username=root
spring.datasource.password=Kabi0522

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

app.admin.email=admin@smartcampus.com
app.admin.password=Admin@123
app.admin.full-name=System Admin
app.admin.it-number=ITADMIN01