spring.application.name=nexahub-api
spring.datasource.url=jdbc:postgresql://localhost:5432/nexahub_db
server.port=8081
spring.datasource.username=postgres
spring.datasource.password=jano123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.seed-default-users=true

app.admin.email=admin@smartcampus.com
app.admin.password=Admin@123
app.admin.full-name=System Admin
app.admin.it-number=ITADMIN01

app.manager.email=manager@smartcampus.com
app.manager.password=Manager@123
app.manager.full-name=Campus Manager
app.manager.it-number=ITMANAGER1

app.technician.email=technician@smartcampus.com
app.technician.password=Tech@123
app.technician.full-name=Maintenance Technician
app.technician.it-number=ITTECH001